/*
* generated by Xtext
*/
package org.xtext.actionscript.contentassist;

import org.xtext.actionscript.contentassist.Abstractactionscript3ProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class actionscript3ProposalProvider extends Abstractactionscript3ProposalProvider {

}
