/*
 * generated by Xtext
 */
package org.xtext.actionscript;

/**
 * Use this class to register components to be used within the IDE.
 */
public class actionscript3RuntimeModule extends org.xtext.actionscript.Abstractactionscript3RuntimeModule {

}
