/*
 * generated by Xtext
 */
package org.xtext.actionscript.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://wiki.eclipse.org/Xtext/Documentation#Formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class actionscript3Formatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		org.xtext.actionscript.services.actionscript3GrammarAccess f = (org.xtext.actionscript.services.actionscript3GrammarAccess) getGrammarAccess();

		//...
	}
}
